# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libgeos-dev

r_packages:
  - Hmisc
  - zoo
  - latticeExtra
  - polynom
  - car
  - reshape
  - rgdal
  - rgeos
  - sp

r_github_packages:
  - josephguillaume/hydromad
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
